name: Merge conflicts labeler
on:
  push:
    branches:
      - master
  pull_request_target:
    types: [synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "merge conflicts"
          removeOnDirtyLabel: "review"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "merge conflicts"
          removeOnDirtyLabel: "techlead"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
